on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: 'Environment to Deploy'
        required: true
        default: 'test'
        type: choice
        options:
          - dev
          - test
          - prod
      stackname:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'The Stack name to deploy.'
        # Default value if no value is explicitly provided
        default: 'test-SolvBasicBusinessDataStack'
        # Input has to be provided for the workflow to run
        required: true

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false # set to false otherwise they will override your PAT
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::828813901875:role/ops-cicd-solv-business
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: 'us-east-1'
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm install
      - name: Build TypeScript
        run: npm run build
      - name: Deploy main stack
        run: npm run deploy:${{ github.event.inputs.environment }} ${{ github.event.inputs.stackname }}
