# on:
# push:
#   branches:
#     - test
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: 'Environment to Deploy'
        required: true
        default: 'test'
        type: choice
        options:
          - dev
          - test
          - prod

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false # set to false otherwise they will override your PAT
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::828813901875:role/ops-cicd-solv-business
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: 'us-east-1'
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm install

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_REPOSITORY: basic-business-data
          IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG"

      - name: Download task definition
        run: aws ecs describe-task-definition --task-definition solv-basic-business-data-definition --query taskDefinition > solv-basic-business-data-definition.json

      - name: Load environment variables and update task definition
        env:
          ENV_FILE: config/.env.${{ github.event.inputs.environment }}
        run: |
          cp solv-basic-business-data-definition.json solv-basic-business-data-definition-updated.json
          while IFS='=' read -r key value
          do
            cleaned_value=$(echo "$value" | sed "s/^'//" | sed "s/'$//")
            echo "$key=$cleaned_value"
            jq --arg k "$key" --arg v "$cleaned_value" '.containerDefinitions[0].environment += [{"name": $k, "value": $v}]' verify-task-definition-updated.json > temp.json && mv temp.json verify-task-definition-updated.json
          done < $ENV_FILE
          mv solv-basic-business-data-definition-updated.json solv-basic-business-data-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: basic-business-data-sync
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: solv-basic-business-data-definition.json
          container-name: basic-business-data
          image: ${{ steps.push-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        id: deploy-basic-business-data-sync
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.basic-business-data-sync.outputs.task-definition }}
          service: solv-basic-business-data-definition-service
          cluster: solv-basic-business-data-cluster
